project_id = "dqlvioijqzlvnvvajmft"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
api_port = 54324
smtp_port = 54326

[storage]
enabled = true
port = 54327
image_transformation_enabled = true

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[edge_runtime]
enabled = true
port = 54329

[[edge_runtime.inspector]]
enabled = true
port = 54330

[functions.ai-insights-engine]
verify_jwt = true

[functions.assets-management]
verify_jwt = true

[functions.audit-management]
verify_jwt = true

[functions.compliance-management]
verify_jwt = true

[functions.custom-forms-management]
verify_jwt = true

[functions.data-collection-management]
verify_jwt = true

[functions.data-import-processor]
verify_jwt = true

[functions.document-ai-processor]
verify_jwt = true

[functions.documents-management]
verify_jwt = true

[functions.esg-dashboard]
verify_jwt = true

[functions.ghg-recalculate]
verify_jwt = true

[functions.license-ai-analyzer]
verify_jwt = false

[functions.license-document-analyzer]
verify_jwt = false

[functions.license-workflow-processor]
verify_jwt = true

[functions.marketplace-matcher]
verify_jwt = true

[functions.performance-analysis]
verify_jwt = true

[functions.gri-content-generator]
verify_jwt = true

[functions.gri-indicator-autofill]
verify_jwt = true

[functions.daton-ai-chat]
verify_jwt = true

[functions.parse-chat-document]
verify_jwt = false

[functions.process-intelligent-alerts]
verify_jwt = false

[functions.predictive-analytics]
verify_jwt = true

[functions.intelligent-document-classifier]
verify_jwt = false

[functions.advanced-document-extractor]
verify_jwt = false

[functions.document-insights-generator]
verify_jwt = true